AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    LambdaFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            Environment: 
                Variables: 
                    SLACK_POST_CHANNEL: "" ### confidential
                    SLACK_OAUTH_TOKEN: "" ### confidential
            FunctionName: "web3-selenium-slackPost"
            Handler: "lambda_function.lambda_handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: "" ### confidential
                S3Key: "cloudformation/lambda/lf_PostSlack.zip"
            MemorySize: 1024
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/web3-selenium-slackPost-role-wt95pkvi"
            Runtime: "python3.7"
            Timeout: 300
            TracingConfig: 
                Mode: "PassThrough"
            Layers: 
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:slack-sdk:1"
            EphemeralStorage: 
                Size: 512

